language: python

python:
  - "3.6"

# Building Specific Branches
branches:
  only:
  - master
  - travis
  
service:
      - docker

# building the docker cotainer
before_install:
      - docker build -t apache2_hello_world src/apache2_hello_world
      - docker run -dit --name apache2_hello_world -p 80:80 apache2_hello_world
      - docker build -t database src/database
      - docker run -dit --name hello-world -p 80:80 database

# command to install dependencies
install:
      - pip3 install -r requirements.txt

# command to run tests
script:
      - pytest testing/

