---
language: python

python:
  - "3.6"

# Building Specific Branches
branches:
  only:
    - master
    - travis
    - Bad3r

service:
  - docker

stages:
  - deploy
  - test
jobs:
  include:
    - stage: deploy
      # building the docker cotainer
      before_install:
        - docker-compose -f src/docker-compose.yml up -d --build

      # command to install dependencies
      install:
        - pip3 install -r requirements.txt

    - stage: test
      # command to run tests
      script:
        - pytest testing/
