version: '3'
services:
  web:
    build: ./web
    links:
      - database
    depends_on:
      - database
    ports:
      - "80:5000"
      
  database:
    build: ./database
    command: --max-allowed-packet=64MB
    ports:
      - "3306:3306"
    environment:
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
      MYSQL_DATABASE: webapp_db


