---
version: '3'
services:
  web:
    build: ./web
    depends_on:
      - database
    networks:
      - csec380
    environment:
      - FLASK_ENV=development
    ports:
      - "80:5000"

  database:
    build: ./database
    restart: always
    networks:
      - csec380
    # healthcheck:
    #   test: "/usr/bin/mysql --user=root --password=toor --host=0.0.0.0 --execute \"USE webapp_db;\""
    #   interval: 3s
    #   timeout: 1s
    #   retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=webapp_db
      - innodb_log_buffer_size=32M
      - innodb_log_file_size=2047M
      - max_allowed_packet=256M

networks:
  csec380:
    driver: bridge
