---
version: '3'
services:
  web:
    build: ./web
    depends_on:
      - database
    networks:
      - csec380
    environment:
      - FLASK_ENV=development
    ports:
      - "80:5000"

  database:
    build: ./database
    command: --max-allowed-packet=64MB
    networks:
      - csec380
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=webapp_db

networks:
  csec380:
    driver: bridge
