version: '3'
services:
  database:
    build: ./database
    command: --max-allowed-packet=64MB
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  web:
    build: ./web
    ports:
      - "80:5000"
  apache2_hello_world:
    build: ./apache2_hello_world
    ports:
      - "8080:80"

